# Generated by Django 5.1 on 2024-09-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='Imagem',
            new_name='imagem',
        ),
    ]
